#
# Copyright (C) 2025 The Android Open Source Project
# Copyright (C) 2025 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/motorola/capri

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# SDK
BOARD_SYSTEMSDK_VERSIONS := 31

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    system \
    system_ext \
    vendor \
    product
BOARD_USES_RECOVERY_AS_BOOT := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a9

# APEX
DEXPREOPT_GENERATE_APEX_IMAGE := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := capri
TARGET_NO_BOOTLOADER := true

# Display
TARGET_SCREEN_DENSITY := 280
TARGET_SCREEN_HEIGHT := 720
TARGET_SCREEN_WIDTH := 1600
DEVICE_RESOLUTION := 1600x720

# Kernel
BOARD_BOOTIMG_HEADER_VERSION := 3
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_CONFIG := capri_defconfig
TARGET_KERNEL_SOURCE := kernel/motorola/capri

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
endif

# Kernel configuration for prebuilt kernel
BOARD_KERNEL_CMDLINE := console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 androidboot.hardware=qcom androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,msm-panel-mapper=1 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=1 androidboot.usbcontroller=4e00000.dwc3 earlycon=msm_geni_serial,0x4a90000 loop.max_part=7 cgroup.memory=nokmem,nosocket androidboot.vbmeta.avb_version=1.0 androidboot.vbmeta.device_state=locked
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)

# Partition Info
BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED := true

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := motorola_dynamic_partitions
BOARD_MOTOROLA_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext product vendor
BOARD_MOTOROLA_DYNAMIC_PARTITIONS_SIZE := 9122611200

# Platform
TARGET_BOARD_PLATFORM := bengal

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

# Ensure recovery image is generated with correct name
TARGET_RECOVERY_IMAGE_NAME := recovery.img

# Recovery Device Modules
TARGET_RECOVERY_DEVICE_MODULES += \
    android.hidl.allocator@1.0 \
    android.hidl.memory@1.0 \
    android.hidl.memory.token@1.0 \
    libdmabufheap \
    libhidlmemory \
    libion \
    libnetutils \
    libxml2 \
    vendor.display.config@1.0 \
    vendor.display.config@2.0

# Recovery init files
TARGET_RECOVERY_DEVICE_MODULES += \
    $(DEVICE_PATH)/recovery/root/android.hardware.boot-service.qti.recovery.rc \
    $(DEVICE_PATH)/recovery/root/init.qcom.recovery.rc \
    $(DEVICE_PATH)/recovery/root/init.recovery.usb.rc \
    $(DEVICE_PATH)/recovery/root/servicemanager.recovery.rc

# Use mke2fs to create ext4 images
TARGET_USES_MKE2FS := true

# Security patch level
VENDOR_SECURITY_PATCH := 2021-08-01

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0

# Rules
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_NINJA_USES_ENV_VARS += RTIC_MPGEN
BUILD_BROKEN_NINJA_USES_ENV_VARS += SDCLANG_AE_CONFIG SDCLANG_CONFIG SDCLANG_SA_ENABLE
BUILD_BROKEN_USES_BUILD_HOST_SHARED_LIBRARY := true
BUILD_BROKEN_USES_BUILD_HOST_STATIC_LIBRARY := true
BUILD_BROKEN_USES_BUILD_HOST_EXECUTABLE := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true

# Ninja build system configurations
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_BUILD_TOP
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_BUILD_PATHS
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_DEV_SCRIPTS
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_EMULATOR_PREBUILT
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_PREBUILTS
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_PRODUCT_OUT
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_HOST_OUT
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_HOST_OUT_EXECUTABLES
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_HOST_OUT_SHARED_LIBRARIES
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_EXECUTABLES
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_SHARED_LIBRARIES
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_INTERMEDIATES
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_HEADERS
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_UNSTRIPPED
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_ROOT
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_DATA
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_ETC
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_VENDOR
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_SYSTEM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_SYSTEM_OTHER
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_SYSTEM_EXT
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_PRODUCT
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_ODM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_VENDOR_DLKM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_SYSTEM_DLKM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_PRODUCT_DLKM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_ODM_DLKM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_SYSTEM_EXT_DLKM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_VENDOR_DLKM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_SYSTEM_DLKM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_PRODUCT_DLKM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_ODM_DLKM
BUILD_BROKEN_NINJA_USES_ENV_VARS += ANDROID_TARGET_OUT_SYSTEM_EXT_DLKM

# Additional build configurations for TWRP
BUILD_BROKEN_VERIFY_USES_LIBRARIES := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true
BUILD_BROKEN_USES_BUILD_HOST_SHARED_LIBRARY := true
BUILD_BROKEN_USES_BUILD_HOST_STATIC_LIBRARY := true
BUILD_BROKEN_USES_BUILD_HOST_EXECUTABLE := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

# Soong configurations
SOONG_CONFIG_NAMESPACES += ufsbsg
SOONG_CONFIG_ufsbsg += ufsframework
SOONG_CONFIG_ufsbsg_ufsframework := bsg

# TWRP Configuration - Based on official TWRP best practices
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_INCLUDE_REPACKTOOLS := true

# TWRP specific build flags
TARGET_RECOVERY_QCOM_RTC_FIX := true
TW_BACKUP_EXCLUSIONS := /data/fonts/files
TW_CUSTOM_CPU_TEMP_PATH := "/sys/devices/virtual/thermal/thermal_zone34/temp"
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"
TW_DEFAULT_BRIGHTNESS := 547
TW_MAX_BRIGHTNESS := 2047
TW_QCOM_ATS_OFFSET := 1666528204500
TW_EXCLUDE_APEX := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_FRAMERATE := 60
TW_INCLUDE_CRYPTO := true
TW_NO_EXFAT_FUSE := true
TW_INCLUDE_RESETPROP := true
TW_USE_SERIALNO_PROPERTY_FOR_DEVICE_ID := true
TW_OVERRIDE_SYSTEM_PROPS := \
    "ro.build.date.utc;ro.bootimage.build.date.utc=ro.build.date.utc;ro.odm.build.date.utc=ro.build.date.utc;ro.product.build.date.utc=ro.build.date.utc;ro.system.build.date.utc=ro.build.date.utc;ro.system_ext.build.date.utc=ro.build.date.utc;ro.vendor.build.date.utc=ro.build.date.utc"

# Additional TWRP flags based on official examples
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_NTFS_3G := true
TW_EXCLUDE_SUPERSU := true
TW_USE_NEW_MINADBD := true
LZMA_RAMDISK_TARGETS := recovery

# Recovery Library Source Files
RECOVERY_LIBRARY_SOURCE_FILES += \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hidl.allocator@1.0.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hidl.memory@1.0.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hidl.memory.token@1.0.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/libdmabufheap.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/libhidlmemory.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/libion.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/libnetutils.so \
    $(TARGET_OUT_SHARED_LIBRARIES)/libxml2.so \
    $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)/vendor.display.config@1.0.so \
    $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)/vendor.display.config@2.0.so

# TWRP Debug Flags
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
TARGET_RECOVERY_DEVICE_MODULES += debuggerd
RECOVERY_BINARY_SOURCE_FILES += $(TARGET_OUT_EXECUTABLES)/debuggerd
TARGET_RECOVERY_DEVICE_MODULES += strace
RECOVERY_BINARY_SOURCE_FILES += $(TARGET_OUT_EXECUTABLES)/strace

# Extras
# TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# Recovery Vendor Dependencies
RECOVERY_VENDOR_PATH := $(DEVICE_PATH)/recovery/root/vendor
TARGET_RECOVERY_VENDOR_MODULES := \
    $(RECOVERY_VENDOR_PATH)/bin \
    $(RECOVERY_VENDOR_PATH)/lib64 \
    $(RECOVERY_VENDOR_PATH)/firmware \
    $(RECOVERY_VENDOR_PATH)/etc

# Recovery System Dependencies
RECOVERY_SYSTEM_PATH := $(DEVICE_PATH)/recovery/root/system
TARGET_RECOVERY_SYSTEM_MODULES := \
    $(RECOVERY_SYSTEM_PATH)/bin \
    $(RECOVERY_SYSTEM_PATH)/etc

# Ensure vendor and system dependencies are included in recovery
# TARGET_RECOVERY_DEVICE_MODULES += \
#     $(RECOVERY_VENDOR_PATH)/etc/* \
#     $(RECOVERY_VENDOR_PATH)/lib64/* \
#     $(RECOVERY_VENDOR_PATH)/firmware/* \
#     $(RECOVERY_SYSTEM_PATH)/bin/* \
#     $(RECOVERY_SYSTEM_PATH)/etc/*
